export default interface ICars{
    id?:string,
    user_id:number,
    vin_number:string,
    plate:string,
    type:string,
    fuel:string,
    make:string,
    model:string,
    engine:string,
    gear_box:string,
    air_conditioner:number,
    color:string,
    message?:any,
}